export const moodProfiles = {
  calm: { energy: 30, valence: 52 },
  focused: { energy: 56, valence: 54 },
  uplifting: { energy: 70, valence: 78 },
  energetic: { energy: 84, valence: 68 },
  melancholic: { energy: 24, valence: 24 },
  warm: { energy: 58, valence: 66 },
};

export const tracks = [
  {
    id: "night-owl",
    title: "Night Owl",
    artist: "Galimatias",
    genres: ["electronic", "downtempo"],
    moods: ["calm", "focused"],
    energy: 34,
    valence: 46,
    tempo: 92,
    key: "A minor",
  },
  {
    id: "falling-back",
    title: "Falling Back",
    artist: "Jon Hopkins",
    genres: ["electronic", "ambient"],
    moods: ["calm", "focused"],
    energy: 41,
    valence: 42,
    tempo: 105,
    key: "C major",
  },
  {
    id: "tide-line",
    title: "Tide Line",
    artist: "Olafur Arnalds",
    genres: ["ambient", "indie"],
    moods: ["calm", "melancholic"],
    energy: 22,
    valence: 28,
    tempo: 88,
    key: "A minor",
  },
  {
    id: "awake",
    title: "Awake",
    artist: "Tycho",
    genres: ["electronic", "ambient"],
    moods: ["focused", "uplifting"],
    energy: 53,
    valence: 61,
    tempo: 97,
    key: "A major",
  },
  {
    id: "a-walk",
    title: "A Walk",
    artist: "Bonobo",
    genres: ["electronic", "downtempo"],
    moods: ["focused", "uplifting"],
    energy: 57,
    valence: 63,
    tempo: 100,
    key: "F major",
  },
  {
    id: "innerbloom",
    title: "Innerbloom",
    artist: "Rufus Du Sol",
    genres: ["electronic", "indie"],
    moods: ["warm", "uplifting"],
    energy: 60,
    valence: 64,
    tempo: 96,
    key: "G major",
  },
  {
    id: "leaning-in",
    title: "Leaning In",
    artist: "The War on Drugs",
    genres: ["indie", "alternative"],
    moods: ["uplifting", "energetic"],
    energy: 69,
    valence: 72,
    tempo: 108,
    key: "D major",
  },
  {
    id: "all-i-need",
    title: "All I Need",
    artist: "Rufus Du Sol",
    genres: ["electronic", "alternative"],
    moods: ["energetic", "uplifting"],
    energy: 76,
    valence: 70,
    tempo: 110,
    key: "E minor",
  },
  {
    id: "midnight-city",
    title: "Midnight City",
    artist: "M83",
    genres: ["electronic", "pop"],
    moods: ["energetic", "uplifting"],
    energy: 82,
    valence: 80,
    tempo: 105,
    key: "B major",
  },
  {
    id: "satellite-mind",
    title: "Satellite Mind",
    artist: "Metric",
    genres: ["alternative", "indie"],
    moods: ["energetic", "focused"],
    energy: 78,
    valence: 67,
    tempo: 120,
    key: "E major",
  },
  {
    id: "retrograde",
    title: "Retrograde",
    artist: "James Blake",
    genres: ["alternative", "electronic"],
    moods: ["melancholic", "calm"],
    energy: 27,
    valence: 21,
    tempo: 82,
    key: "D minor",
  },
  {
    id: "motion-picture",
    title: "Motion Picture Soundtrack",
    artist: "Radiohead",
    genres: ["alternative", "ambient"],
    moods: ["melancholic", "calm"],
    energy: 18,
    valence: 18,
    tempo: 74,
    key: "C major",
  },
  {
    id: "holocene",
    title: "Holocene",
    artist: "Bon Iver",
    genres: ["indie", "alternative"],
    moods: ["calm", "warm"],
    energy: 29,
    valence: 39,
    tempo: 84,
    key: "F sharp major",
  },
  {
    id: "your-hand",
    title: "Your Hand in Mine",
    artist: "Explosions in the Sky",
    genres: ["indie", "ambient"],
    moods: ["warm", "uplifting"],
    energy: 62,
    valence: 67,
    tempo: 116,
    key: "D major",
  },
  {
    id: "go",
    title: "Go",
    artist: "The Chemical Brothers",
    genres: ["electronic", "pop"],
    moods: ["energetic", "uplifting"],
    energy: 88,
    valence: 76,
    tempo: 124,
    key: "A minor",
  },
  {
    id: "open-eye-signal",
    title: "Open Eye Signal",
    artist: "Jon Hopkins",
    genres: ["electronic", "ambient"],
    moods: ["focused", "energetic"],
    energy: 74,
    valence: 58,
    tempo: 118,
    key: "C sharp minor",
  },
  {
    id: "sunset-lover",
    title: "Sunset Lover",
    artist: "Petit Biscuit",
    genres: ["electronic", "downtempo"],
    moods: ["calm", "warm"],
    energy: 36,
    valence: 58,
    tempo: 90,
    key: "G major",
  },
  {
    id: "weights",
    title: "Weights",
    artist: "Daughter",
    genres: ["indie", "alternative"],
    moods: ["melancholic", "warm"],
    energy: 31,
    valence: 30,
    tempo: 86,
    key: "E minor",
  },
  {
    id: "we-move-lightly",
    title: "We Move Lightly",
    artist: "Dustin O'Halloran",
    genres: ["ambient", "indie"],
    moods: ["calm", "focused"],
    energy: 16,
    valence: 40,
    tempo: 70,
    key: "C major",
  },
  {
    id: "something-good",
    title: "Something Good Can Work",
    artist: "Two Door Cinema Club",
    genres: ["indie", "pop"],
    moods: ["uplifting", "energetic"],
    energy: 81,
    valence: 83,
    tempo: 119,
    key: "D major",
  },
  {
    id: "dayvan-cowboy",
    title: "Dayvan Cowboy",
    artist: "Boards of Canada",
    genres: ["electronic", "ambient"],
    moods: ["warm", "focused"],
    energy: 48,
    valence: 55,
    tempo: 101,
    key: "B flat major",
  },
  {
    id: "first-breath",
    title: "First Breath After Coma",
    artist: "Explosions in the Sky",
    genres: ["indie", "ambient"],
    moods: ["focused", "uplifting"],
    energy: 65,
    valence: 62,
    tempo: 112,
    key: "E major",
  },
];
